### ISSUE TITLE
Installation of package error pyunormalize

### ISSUE THREAD

**Issue by RoxyBlockChain** [mlodewijck/pyunormalize#4]
Installation of package error

```Collecting pyunormalize
  Using cached pyunormalize-15.1.0.tar.gz (515 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<31 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('C:\\Users\\Roxy\\AppData\\Local\\Temp\\pip-install-zer6lqac\\pyunormalize_5f136f9490f24ea9826d79943c66b9ee\\setup.py',), "<pip-setuptools-caller>", "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Roxy\AppData\Local\Temp\pip-install-zer6lqac\pyunormalize_5f136f9490f24ea9826d79943c66b9ee\setup.py", line 19, in <module>
          version=get_version(),
                  ~~~~~~~~~~~^^
        File "C:\Users\Roxy\AppData\Local\Temp\pip-install-zer6lqac\pyunormalize_5f136f9490f24ea9826d79943c66b9ee\setup.py", line 12, in get_version
          return locals()["__version__"]
                 ~~~~~~~~^^^^^^^^^^^^^^^
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Jenselme** [comment]
I have the same issue on linux on Python 3.13. Works fine on Python 3.12

**Comment by mlodewijck** [comment]
Thank you for reporting this issue. It appears to be related to a change introduced in Python version 3.13, as detailed in the [Defined mutation semantics for `locals()`](https://docs.python.org/3.13/whatsnew/3.13.html#defined-mutation-semantics-for-locals) section. This issue will be resolved in the upcoming release of pyunormalize (version 16.0.0), which will be available soon.

**Comment by mlodewijck** [comment]
This problem should no longer occur. Please confirm.

**Comment by Jenselme** [comment]
Just tested in a Python 3.13 container (using RC2) and I can confirm the package installs and runs fine. Thanks!

**Comment by mlodewijck** [comment]
Thanks a million!
